version: '3'

services:
  apisolid-db:
    image: postgres:latest
    volumes:
      - apisolid-pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: apisolid
      POSTGRES_PORT: 5432

volumes:
  apisolid-pgdata:
